### PR TITLE
Merge upstream for `invoke-polymorphic`

### LINKED ISSUE #2022: [Bug] dexbuilder does not support dalvik bytecode  version 36+
版本号高于35的字节码在重生成后损坏
https://github.com/SakuraKoi/DgLabUnlocker/issues/14

```
----part 3 start----
[ 2022-05-17T21:02:33.441    10264: 27190: 27190 I/LSPosed-Bridge  ] Loading module sakura.kooi.dglabunlocker from /data/app/~~NXu5diOZ8Mwa5oRukWwDCg==/sakura.kooi.dglabunlocker-ZTL1k6_2f8085EeGGs__eQ==/base.apk
[ 2022-05-17T21:02:33.463    10264: 27190: 27190 I/LSPosed-Bridge  ]   Loading class sakura.kooi.dglabunlocker.XposedModuleInit
[ 2022-05-17T21:02:33.725    10264: 27190: 27190 E/LSPosed-Bridge  ] java.lang.VerifyError: Verifier rejected class sakura.kooi.dglabunlocker.variables.ModuleSettings: void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context) failed to verify: void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context): [0x2] void sakura.kooi.dglabunlocker.variables.ModuleSettings.showSettingsDialog(android.content.Context): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup' (declaration of 'sakura.kooi.dglabunlocker.variables.ModuleSettings' appears in Anonymous-DexFile@1437296361)
 at sakura.kooi.dglabunlocker.variables.ModuleSettings.loadConfiguration(Unknown Source:0)
 at sakura.kooi.dglabunlocker.XposedModuleInit.onAppLoaded(XposedModuleInit.java:109)
 at sakura.kooi.dglabunlocker.XposedModuleInit.access$000(XposedModuleInit.java:37)
 at sakura.kooi.dglabunlocker.XposedModuleInit$1.afterHookedMethod(XposedModuleInit.java:87)
 at KC.Aa.LLWKGBiWaQht.nrd.XposedBridge$AdditionalHookInfo.callback(Unknown Source:147)
 at LSPHooker_.attachBaseContext(Unknown Source:11)
 at android.app.Application.attach(Application.java:338)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1192)
 at android.app.LoadedApk.makeApplication(LoadedApk.java:1356)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6723)
 at android.app.ActivityThread.access$1500(ActivityThread.java:256)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2091)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7870)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

```
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge: java.lang.VerifyError: Verifier rejected class sakura.kooi.dglabunlocker.utils.FieldAccessor: java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get() failed to verify: java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get(): [0x2] java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get(): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup'
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:  java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get(java.lang.Object) failed to verify: java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get(java.lang.Object): [0x2] java.lang.Object sakura.kooi.dglabunlocker.utils.FieldAccessor.get(java.lang.Object): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup'
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:  void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object) failed to verify: void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object): [0x2] void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup'
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:  void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object, java.lang.Object) failed to verify: void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object, java.lang.Object): [0x2] void sakura.kooi.dglabunlocker.utils.FieldAccessor.set(java.lang.Object, java.lang.Object): [0x2] 'this' argument 'Reference: java.lang.invoke.MethodHandle' not instance of 'Precise Reference: java.lang.invoke.MethodHandles$Lookup' (declaration of 'sakura.kooi.dglabunlocker.utils.FieldAccessor' appears in Anonymous-DexFile@370493346!classes4.dex)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.ver.AbstractVersionedCompatibilityProvider.lookupField(AbstractVersionedCompatibilityProvider.java:41)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.ver.Version132.initializeAccessors(Version132.java:17)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.ver.AbstractVersionedCompatibilityProvider.initializeAccessors(AbstractVersionedCompatibilityProvider.java:24)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.XposedModuleInit.onAppLoaded(XposedModuleInit.java:112)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.XposedModuleInit.-$$Nest$monAppLoaded(Unknown Source:0)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at sakura.kooi.dglabunlocker.XposedModuleInit$1.afterHookedMethod(XposedModuleInit.java:79)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(XposedBridge.java:484)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at LSPHooker_.attachBaseContext(Unknown Source:11)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.Application.attach(Application.java:331)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.Instrumentation.newApplication(Instrumentation.java:1179)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.LoadedApk.makeApplication(LoadedApk.java:1361)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6714)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.ActivityThread.access$1500(ActivityThread.java:252)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2058)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.os.Handler.dispatchMessage(Handler.java:106)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.os.Looper.loopOnce(Looper.java:346)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.os.Looper.loop(Looper.java:475)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at android.app.ActivityThread.main(ActivityThread.java:7889)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at java.lang.reflect.Method.invoke(Native Method)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
07-05 01:37:52.908  9523  9523 E LSPosed-Bridge:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
```

### PR DESCRIPTION
**Pull request by yujincheng08**
Fix LSPosed/LSPosed#2022

### CODE REVIEW

File: slicer/reader.cc [hunk 1]
```diff
@@ -890,6 +891,12 @@ void Reader::ParseInstructions(slicer::ArrayView<const dex::u2> code) {
         index = dex_instr.vB;
         break;
 
+      case dex::k45cc:
+      case dex::k4rcc:
+        index = dex_instr.vB;
+            index2 = dex_instr.arg[4];
```
Comment (canyie) [inline slicer/reader.cc]: ?

**Review by kotori2 — APPROVED** [review]
